"C:\Workspace\Github\StockManager\StockManagerDB\AStyle.exe" --style=allman --add-one-line-braces --max-code-length=80 --break-after-logical --indent-switches --convert-tabs --indent=spaces=4 --pad-header --pad-comma --pad-oper --max-continuation-indent=80 --attach-closing-while --align-pointer=type --squeeze-ws --fill-empty-lines --squeeze-lines=1 $1
echo Press Enter to exit...
read
